name: fson_room_app
description: FSON Room App.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio_wrapper:
    git:
      url: https://github.com/kmlgkcy/dio_wrapper.git
      ref: v0.0.3

  url_launcher: ^6.1.10
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  slang: ^3.12.0
  slang_flutter: ^3.12.0
  flutter_dropzone_web: ^3.0.8
  flutter_dropzone: ^3.0.5
  shared_preferences: ^2.0.20

  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  slang_build_runner: ^3.12.0
  mobx_codegen: ^2.1.1

flutter:
  uses-material-design: true
