targets:
  $default:
    builders:
      slang_build_runner:
        options:
          input_directory: assets/i18n
          base_locale: en
          fallback_strategy: base_locale
          output_file_name: translations.g.dart
          flutter_integration: true
          translation_class_visibility: private
          key_case: snake
          string_interpolation: double_braces
